# Generated by Django 4.2 on 2026-01-14 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(db_index=True, max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientemodel',
            index=models.Index(fields=['documento'], name='clientes_documen_0d1be1_idx'),
        ),
        migrations.AddIndex(
            model_name='clientemodel',
            index=models.Index(fields=['email'], name='clientes_email_fb2cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientemodel',
            index=models.Index(fields=['ativo'], name='clientes_ativo_4789c8_idx'),
        ),
    ]
