# Generated by Django 4.2 on 2026-01-14 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendedormodel',
            index=models.Index(fields=['email'], name='vendedores_email_6f4ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedormodel',
            index=models.Index(fields=['ativo'], name='vendedores_ativo_674d19_idx'),
        ),
    ]
