# Generated by Django 4.2 on 2026-01-14 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_vendedormodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(db_index=True, max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fornecedormodel',
            index=models.Index(fields=['cnpj'], name='fornecedore_cnpj_9b0e72_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedormodel',
            index=models.Index(fields=['ativo'], name='fornecedore_ativo_bee848_idx'),
        ),
    ]
