version: '3.8'

services:
  # =====================================================
  # 🗄️ Serviço do Banco de Dados PostgreSQL
  # =====================================================
  postgres-db:
    image: postgres:15-alpine
    container_name: sunops_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - sunops_network

  # =====================================================
  # 🔄 CACHE: Serviço do Redis
  # =====================================================
  sunops-redis:
    image: redis:7-alpine
    container_name: sunops_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sunops_network

  # =====================================================
  # 📦 API de Catálogo (Flask) - NOVO SERVIÇO
  # =====================================================
  catalogo-api:
    container_name: sunops_catalogo_api
    build:
      context: ./catalogo-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./catalogo-api/data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      # --- CORREÇÃO: Apontar a API Flask para o serviço Redis correto ---
      - REDIS_HOST=sunops-redis
      - REDIS_PORT=6379
      # ----------------------------------------------------------------
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - sunops_network
    restart: unless-stopped

  # =====================================================
  # ⚙️ Serviço da API Backend (FastAPI)
  # =====================================================
  sunops-api:
    container_name: sunops_api
    build:
      context: ./backend
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres-db

      # Variáveis de autenticação
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      # Variáveis do primeiro admin
      FIRST_ADMIN_EMAIL: ${FIRST_ADMIN_EMAIL}
      FIRST_ADMIN_PASSWORD: ${FIRST_ADMIN_PASSWORD}
      FIRST_ADMIN_NAME: ${FIRST_ADMIN_NAME}

      # Variáveis do Redis
      REDIS_HOST: sunops-redis
      REDIS_PORT: 6379
      REDIS_DB: 0

      # URL da API de Catálogo (opcional, caso o backend precise consumir)
      CATALOGO_API_URL: http://catalogo-api:5001

    depends_on:
      postgres-db:
        condition: service_healthy
      sunops-redis:
        condition: service_started
      catalogo-api:
        condition: service_healthy
    networks:
      - sunops_network

  # =====================================================
  # 💻 Serviço do Frontend React/Vite (SunOps)
  # =====================================================
  sunops-frontend:
    container_name: sunops_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_CATALOGO_API_URL=http://localhost:5001
    depends_on:
      - sunops-api
      - catalogo-api
    networks:
      - sunops_network

# =====================================================
# 📦 Redes e Volumes Persistentes
# =====================================================
networks:
  sunops_network:
    driver: bridge

volumes:
  postgres_data:
    name: sunops-postgres-data
  redis_data:
    name: sunops-redis-data
