version: '3.8'

services:
  # =====================================================
  # 🗄️ Serviço do Banco de Dados PostgreSQL
  # =====================================================
  postgres-db:
    image: postgres:15-alpine
    container_name: sunops_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"  # Mapeia porta do container para a porta do host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # =====================================================
  # ⚙️ Serviço da API Backend (FastAPI)
  # =====================================================
  sunops-api:
    container_name: sunops_api
    build:
      context: ./backend  # Pasta do backend
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"  # Porta da API no host
    # Descomente a linha abaixo se quiser hot-reload no backend (modo dev)
    # volumes:
    #   - ./backend:/app
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres-db

      # Variáveis de autenticação
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      # Variáveis do primeiro admin (setup inicial)
      FIRST_ADMIN_EMAIL: ${FIRST_ADMIN_EMAIL}
      FIRST_ADMIN_PASSWORD: ${FIRST_ADMIN_PASSWORD}
      FIRST_ADMIN_NAME: ${FIRST_ADMIN_NAME}

    depends_on:
      postgres-db:
        condition: service_healthy

  # =====================================================
  # 💻 Serviço do Frontend React/Vite (SunOps)
  # =====================================================
  sunops-frontend:
    container_name: sunops_frontend
    build:
      context: ./frontend  # Pasta do frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volume anônimo para node_modules
    ports:
      - "5173:5173"  # Porta do Vite no host
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - sunops-api

# =====================================================
# 📦 Volumes Persistentes
# =====================================================
volumes:
  postgres_data:
    name: sunops-postgres-data
