# Generated by Django 4.2 on 2026-01-14 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='marcamodel',
            index=models.Index(fields=['nome'], name='marcas_nome_275445_idx'),
        ),
        migrations.AddIndex(
            model_name='marcamodel',
            index=models.Index(fields=['ativo'], name='marcas_ativo_531532_idx'),
        ),
    ]
