# Generated by Django 4.2 on 2026-01-14 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InversorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('marca_id', models.UUIDField()),
                ('fornecedor_id', models.UUIDField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('STRING', 'String'), ('MICROINVERSOR', 'Microinversor')], default='STRING', max_length=20)),
                ('fases', models.IntegerField(choices=[(1, 'Monofásico'), (3, 'Trifásico')], default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
                'db_table': 'inversores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PainelModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('marca_id', models.UUIDField()),
                ('fornecedor_id', models.UUIDField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('MONOCRISTALINO', 'Monocristalino'), ('POLICRISTALINO', 'Policristalino')], default='MONOCRISTALINO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Painel Solar',
                'verbose_name_plural': 'Painéis Solares',
                'db_table': 'paineis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='painelmodel',
            index=models.Index(fields=['marca_id'], name='paineis_marca_i_68c947_idx'),
        ),
        migrations.AddIndex(
            model_name='painelmodel',
            index=models.Index(fields=['fornecedor_id'], name='paineis_fornece_466ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='painelmodel',
            index=models.Index(fields=['ativo'], name='paineis_ativo_a0339f_idx'),
        ),
        migrations.AddIndex(
            model_name='inversormodel',
            index=models.Index(fields=['marca_id'], name='inversores_marca_i_bd8f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='inversormodel',
            index=models.Index(fields=['fornecedor_id'], name='inversores_fornece_a8391e_idx'),
        ),
        migrations.AddIndex(
            model_name='inversormodel',
            index=models.Index(fields=['ativo'], name='inversores_ativo_da4632_idx'),
        ),
    ]
