# Generated by Django 4.2 on 2026-01-14 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_nome', models.CharField(max_length=200)),
                ('acao', models.CharField(max_length=100)),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_novo', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_financeira',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_percentual', models.DecimalField(decimal_places=4, default=0.05, help_text='Comissão (ex: 0.05 = 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('imposto_percentual', models.DecimalField(decimal_places=4, default=0.06, help_text='Impostos (ex: 0.06 = 6%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('margem_lucro_minima', models.DecimalField(decimal_places=4, default=0.2, help_text='Margem mínima (ex: 0.20 = 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('custo_montagem_por_painel', models.DecimalField(decimal_places=2, default=70.0, help_text='Custo montagem/painel (R$)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_operacional_fixo', models.DecimalField(decimal_places=2, default=500.0, help_text='Custo operacional fixo (R$)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('arredondamento_multiplo', models.IntegerField(default=100, help_text='Múltiplo arredondamento', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
                'db_table': 'configuracao_financeira',
            },
        ),
    ]
