"""Adiciona data_criacao a tabela clientes

Revision ID: 489c478bd672
Revises: f0d21d7f67d6
Create Date: 2025-10-30 01:02:00.630410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489c478bd672'
down_revision: Union[str, Sequence[str], None] = 'f0d21d7f67d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'data_criacao')
    # ### end Alembic commands ###
