"""feat: cria tabelas iniciais do sunops

Revision ID: d7a5b3e28df5
Revises: 
Create Date: 2025-10-29 01:28:56.937735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a5b3e28df5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_razao_social', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PESSOA_FISICA', 'PESSOA_JURIDICA', name='tipocliente'), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('configuracoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margem_lucro_padrao', sa.Float(), nullable=False),
    sa.Column('percentual_comissao_padrao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GESTOR', 'VENDEDOR', 'SUPORTE', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('potencia_kwp', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('EM_NEGOCIACAO', 'APROVADO', 'EM_ANALISE', 'INSTALADO', 'CANCELADO', name='projetostatus'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propostas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NOVA', 'ENVIADA', 'EM_NEGOCIACAO', 'GANHA', 'PERDIDA', name='propostastatus'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA_PROJETO', 'CUSTO_EQUIPAMENTO', 'COMISSAO_A_PAGAR', 'OUTRA_RECEITA', 'OUTRA_DESPESA', name='tipotransacao'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'ATRASADA', 'CANCELADA', name='statustransacao'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('propostas')
    op.drop_table('projetos')
    op.drop_table('users')
    op.drop_table('configuracoes_financeiras')
    op.drop_table('clientes')
    # ### end Alembic commands ###
