"""Implementa arquitetura de catalogo de equipamentos

Revision ID: f08a7b534f38
Revises: 489c478bd672
Create Date: 2025-10-30 01:24:41.874651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08a7b534f38'
down_revision: Union[str, Sequence[str], None] = '489c478bd672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias_equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribuidores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribuidores_nome'), 'distribuidores', ['nome'], unique=True)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome_modelo', sa.String(length=255), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('potencia_w', sa.Float(), nullable=True),
    sa.Column('dados_tecnicos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_nome_modelo'), 'equipamentos', ['nome_modelo'], unique=True)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distribuidor_id', sa.Integer(), nullable=False),
    sa.Column('nome_kit', sa.String(length=255), nullable=False),
    sa.Column('codigo_kit', sa.String(length=100), nullable=True),
    sa.Column('custo_total_kit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['distribuidor_id'], ['distribuidores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_codigo_kit'), 'kits', ['codigo_kit'], unique=False)
    op.create_table('catalogo_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('distribuidor_id', sa.Integer(), nullable=False),
    sa.Column('codigo_distribuidor', sa.String(length=100), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('data_atualizacao_preco', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['distribuidor_id'], ['distribuidores.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_itens_codigo_distribuidor'), 'catalogo_itens', ['codigo_distribuidor'], unique=False)
    op.create_table('proposta_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impostos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margem', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kit_items_association',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_itens.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('kit_id', 'catalogo_item_id')
    )
    op.add_column('propostas', sa.Column('nome', sa.String(length=255), nullable=True))
    op.add_column('propostas', sa.Column('descricao', sa.String(length=1000), nullable=True))
    op.add_column('propostas', sa.Column('potencia_kwp', sa.Float(), nullable=True))
    op.add_column('propostas', sa.Column('premissas', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'premissas')
    op.drop_column('propostas', 'potencia_kwp')
    op.drop_column('propostas', 'descricao')
    op.drop_column('propostas', 'nome')
    op.drop_table('kit_items_association')
    op.drop_table('proposta_itens')
    op.drop_index(op.f('ix_catalogo_itens_codigo_distribuidor'), table_name='catalogo_itens')
    op.drop_table('catalogo_itens')
    op.drop_index(op.f('ix_kits_codigo_kit'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_equipamentos_nome_modelo'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_distribuidores_nome'), table_name='distribuidores')
    op.drop_table('distribuidores')
    op.drop_table('categorias_equipamentos')
    # ### end Alembic commands ###
