"""Adiciona data_atualizacao a tabela propostas

Revision ID: f0d21d7f67d6
Revises: d7a5b3e28df5
Create Date: 2025-10-30 01:00:18.064823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d21d7f67d6'
down_revision: Union[str, Sequence[str], None] = 'd7a5b3e28df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'data_atualizacao')
    # ### end Alembic commands ###
