# Generated by Django 4.2 on 2026-01-14 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('vendedor_id', models.UUIDField()),
                ('kit_nome', models.CharField(max_length=200)),
                ('kit_itens', models.JSONField(default=list)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='RASCUNHO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'orcamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamentomodel',
            index=models.Index(fields=['cliente_id'], name='orcamentos_cliente_d992e8_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentomodel',
            index=models.Index(fields=['vendedor_id'], name='orcamentos_vendedo_34e7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentomodel',
            index=models.Index(fields=['status'], name='orcamentos_status_641434_idx'),
        ),
    ]
