# Generated by Django 4.2 on 2026-01-14 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_host', models.CharField(default='postgres', max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['nome'],
            },
        ),
    ]
