# Generated by Django 4.2 on 2026-01-14 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('vendedor_id', models.CharField(max_length=100)),
                ('admin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assunto', models.CharField(default='Solicitação de orçamento', max_length=255)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('RESOLVIDA', 'Resolvida'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_conversas',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('remetente_id', models.CharField(max_length=100)),
                ('tipo_remetente', models.CharField(choices=[('ADMIN', 'Admin'), ('VENDEDOR', 'Vendedor'), ('IA', 'IA')], max_length=10)),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida')], default='ENVIADA', max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
            ],
            options={
                'db_table': 'chat_mensagens',
                'ordering': ['timestamp'],
            },
        ),
    ]
